version: "2"

issues:
  max-same-issues: 0
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - nlreturn
    - noinlineerr
    - wsl
    - wsl_v5
  settings:
    errcheck:
      exclude-functions:
        io.WriteString
    embeddedstructfieldcheck:
      empty-line: false
      forbid-mutex: true
    gosec:
      excludes:
        - G703
        - G706
    mnd:
      ignored-functions:
        - caller
        - Output
        - os.MkdirAll
        - os.OpenFile
    varnamelen:
      ignore-decls:
        - r *http.Request
        - w http.ResponseWriter
  exclusions:
    generated: lax
    presets:
      #- comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
