version: "2"

issues:
  max-same-issues: 0
linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - nlreturn
    - wsl
    - nolintlint
  exclusions:
    generated: lax
    presets:
      #- comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
